name: "CI: Synchronise Labels"

on:
  workflow_call:
    secrets:
      REPO_TOKEN:
        description: "Token to access repository and manage labels"
        required: true

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - name: "[INIT] Checkout current repository"
        uses: actions/checkout@v6

      - name: "[INIT] Checkout labels"
        uses: actions/checkout@v6
        with:
          repository: kludge-cs/.github
          path: .github-shared

      - name: "[EXEC] Synchronize labels"
        uses: crazy-max/ghaction-github-labeler@v5
        with:
          github-token: ${{ secrets.REPO_TOKEN }}
          yaml-file: .github-shared/.github/labels.yml
